blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('register/', include('crud.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from . import views
from django.urls import path

app_name = 'blogapp'

urlpatterns = [
    path('', views.index, name= 'post'),
    path('<int:number>/<slug:title>/', views.single_post, name= 'single_post'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>',views.index, name='post_list_by_tag'),

]

crud/urls.py
from . import views
from django.urls import path


urlpatterns = [

    path('', views.register, name= 'register'),
    path('<int:rm_number>/rm/', views.delete, name= 'delete'),
    path('<int:data_number>/edit/', views.edit, name= 'edit'),

]

blogapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class Post(models.Model):
    objects = None
    STATUS_CHOICE = (('draft','Draft'),('published','Published'),)
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images")
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_post')
    body = RichTextField(blank=True,null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICE, default='draft')
    tag_obj = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse("blogapp:single_post",
         args=[self.id,self.slug])
    

    def __str__(self):
        return self.headline



class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comment_here') # this related_name is used in views
    name = models.CharField(max_length=40)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comments by {self.name} on {self.post}'

crud/models.py
from django.db import models


class Register(models.Model):

    objects = None
    name = models.CharField(max_length=30)
    roll = models.IntegerField()
    age = models.IntegerField()
    def __str__(self):
        return self.name

blogapp/forms.py
from django import forms
from . models import Comments

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name','email','body')

blogapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Post
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag # Tag is build in class of taggit Tag has 2 objects slug and name


def index(request,tag_slug=None):
    template = 'index.html'
    post = Post.objects.all() # to call all post

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug) # Tag has 2 object name and slug. exact slug is brought here
        post = post.filter(tag_obj__in=[tag]) # now all posts  are filtering ever the exact slug


    paginator = Paginator(post,3)
    page = request.GET.get('page')
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)

    except EmptyPage:
        post = paginator.page(paginator.num_pages)

    context = {
        'page_obt':page,
        'posts': post,
        'tag':tag,


    }

    return render(request, template_name=template,context=context)


def single_post(request,number,title):
    template = 'single_post.html'
    post = get_object_or_404(Post,slug = title, id = number)
    comment = post.comment_here.filter(active=True) # we got post from the up line and comment_here is taken from related_name of Comments model's post object
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentForm()
    context = {
        'post':post,
        'comments':comment,
        'new_comment':new_comment,
        'comment_form':comment_form,
    }
    return render(request,template_name=template,context=context)




def post_share(request,post_id):

    post = get_object_or_404(Post,id= post_id,status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.Post)
        if form.is_valid():
            cd = form.cleaned_data
            # .... send email....
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']}  recommends you read" f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject,message,'naeemislam13790@gmail.com', [cd['to']])
            sent = True


    else:
        form = EmailPostForm()
    context = {
        'post':post,
        'form':form,
        'sent':sent
    }
    return render(request,'test.html', context=context)

crud/views.py
from django.shortcuts import render,redirect
from .models import Register
from .form import StudentRegister


def register(request):
    template = "register.html"
    form = StudentRegister()
    result = Register.objects.all()
    if request.method == 'POST':
        sform = StudentRegister(request.POST)
        if sform.is_valid():
            sform.save()
            return redirect('/register/')

    context = {

        'form': form,
        'results': result,

    }

    return render(request, template_name=template,context=context)


def delete(request,rm_number):
    if request.method == 'POST':
        data = Register.objects.get(id=rm_number)
        data.delete()
        return redirect('/register/')

def edit(request,data_number):

    template = 'edit.html'
    data = Register.objects.get(id=data_number)
    if request.method == 'POST':
     form = StudentRegister(request.POST,instance=data)
     if form.is_valid():
        form.save()
        return redirect('/register/')
    context = {
        'form':form,
    }
    return render(request, template_name=template,context=context)

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">

</form>
</body>
</html>

templates/hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<h1></h1>
  {% if sent %}
   <h1> Email sent successfully </h1>
   <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_date.to }}</p>
  {% else %}
    <h1> Share "{{ post.title }}" by email </h1>
    <form method="Post">

        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send Email">
    </form>
  {% endif %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'register' %}">CRUD</a>


  {% if tag %}
    <h2> Posts tagged with "{{tag.name}}"</h2>
  {% endif %}



   {% for post in posts %}
   <h2> <a href="{{ post.get_absolute_url }}">{{post.headline}}</a> </h2>
   <p>{{post.publish}} by {{post.author}} </p>



    Tags:
      {% for tag in post.tag_obj.all %}
         <a href="{% url 'blogapp:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
         </a>
         {% if not forloop.last %},
         {% endif %}
      {% endfor %}





   <p>{{post.body | safe | truncatewords:30 | linebreaks }}</p>

   {% endfor %}
   {% include 'paginator.html' with page_obt=posts %}



</body>
</html>

templates/paginator.html
{% if page_obt.has_previous %}
  <a href='?page={{page_obt.previous_page_number}}'> Previous </a>
{% endif %}

Page {{page_obt.number}} of {{page_obt.paginator.num_pages}}

{% if page_obt.has_next %}
  <a href='?page={{page_obt.next_page_number}}'> Next </a>
{% endif %}


templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

</head>
<body>
<h1>this is a test bro</h1>
<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}
 <input type="submit" value="Submit">

</form>
<br/>
<br/>
{% if results %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Roll</th>
      <th scope="col">Age</th>
      <th scope="col">Delete</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
{% for result in results %}

  <tbody>
    <tr>
      <th scope="row">{{result.id}}</th>
      <td>{{result.name}}</td>
      <td>{{result.roll}}</td>
      <td>{{result.age}}</td>
      <td>
        <form method="POST" action="{% url 'delete' result.id %}">
           {% csrf_token %}
            <input type="submit" value="Delete">

        </form>
      </td>

      <td>
         <form method="POST" action="{% url 'edit' result.id %}">
           {% csrf_token %}

           <input type="submit" value="Edit">
         </form>
      </td>
    </tr>
  </tbody>

{% endfor %}
</table>
{% endif %}

</body>
</html>

templates/single_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img class="featured_image" src="{{ post.thumbnail.url }}">
    <h1>{{post.headline}}</h1>
    <h4>{{post.sub_headline}}</h4>
    <p>{{post.publish}} by {{post.author}}</p>
    <p>{{post.body | safe | linebreaks }}</p>
    <p><a href="{% url 'blogapp:post_share' post.id %}"> Share this post </a></p>

  <h2>
       comment
  </h2>

{% for comment in comments %}

    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
        </p>
        {{ comment.body }}
    </div>
    {% empty %}
    <p>
        There are no comments yet
    </p>

{% endfor %}

{% if new_comment %}
<h2> your comment has been added </h2>

{% else %}
<h2>
     Add a new comment
</h2>

<form method="POST">
 {{ comment_form.as_p }}
{% csrf_token %}
    <p> <input type="submit" value="Add Comment"></p>
</form>

{% endif %}
</body>
</html>